### ISSUE TITLE
2- Parser : test bench no test running

### ISSUE THREAD

**Issue by chocovore17** [LangProc/langproc-2019-lab#10]
After pulling new changes with the updates for the makefile and test bench, the tests don't run. It seems that it never enters the "while loop", even though it prints 
`checking that good expression are parsed". `
I am not sure it comes from my code since it runs fine when I test it manually.
Is it because of 
`./test_parser.sh: line 104: lsb_release: command not found` ?

**Comment by tobhil98** [comment]
What environment are you running it on? Does it work when you are running it with the old test_parser.sh?

**Comment by chocovore17** [comment]
Here is what I get.
I am not using Linux, but this should be fine (I think..)
```
c++  -std=c++11 -W -Wall -g -Wno-unused-parameter -I include  -c -o src/eval_expr.o src/eval_expr.cpp
mkdir -p bin
g++ -std=c++11 -W -Wall -g -Wno-unused-parameter -I include -o bin/eval_expr src/eval_expr.o src/maths_parser.tab.o src/maths_lexer.yy.o

=========================================
Checking that good expressions are parsed
rm: test/valid_expressions.got.txt: No such file or directory

============================================
Checking that bad expressions are not parsed

########################################
Passed 0 out of 0 checks.

./test_parser.sh: line 104: lsb_release: command not found
```

**Comment by tobhil98** [comment]
Is your "test_parser.sh" and your "tests" folder in the same directory as your "makefile"?

Also delete lines 101-115 in the test_parser.sh file to get rid of the "lsb_release: command not found" error. It is only there to remind you to run your exercise on a lab machine before submitting.

**Comment by chocovore17** [comment]
Same directory for tests makefile and bash.
 I also tried creating a new rep and pulling all of the parser repository from master branch. Testbench should fail when I uncomment the "todo-1", yet I get the same error of 0 out of 0 tests.

**Comment by akowal3** [comment]
I was able to reproduce the error, which you have experienced, and the problem appears to be line endings of `valid_expression.input.txt` and `invalid_expression.input.txt`.

It happens when line endings of those files are set to CLRF (Windows) and not LF (Unix). To solve the issue, I suggest manually changing line endings to Unix (bottom right corner in Atom should have a button to do so)

Alternatively, you can install dos2unix or fromdos to do it automatically, or comment out the if-else statement from line 5 to 24, and adding new line underneath with `DOS2UNIX="sed -e s/\r//g -"`. 
This step was able to solve the issue on my Linux machine. I don't know whether it will work on another os.

**Comment by chocovore17** [comment]
Thanks, after changing line endings, it still doesn't solve it for mac .

**Comment by ymherklotz** [comment]
Hmm, the script change was only minor and should have fixed the line ending problem for mac, but I couldn't test it on mac myself. I was just going by what other people were saying.

Could you maybe modify the script and add

```bash
set -x
```

At the very top and then run it again? This should produce better output.

Otherwise, you could try removing the `dos2unix` completely if you have run it manually, as this is not needed when windows is not used at all. This can be done by removing all the `| ${DOS2UNIX}`, which the following command achieves (at least in linux...):

```bash
sed -i 's: | \${DOS2UNIX}::g' test_parser.sh
```

If the latter works, I would love to know why that kind of piping doesn't seem to work in OSX.

**Comment by ymherklotz** [comment]
Another solution would be to use the `vagrant` box that comes with the repository. This would make sure that everything works as intended.

**Comment by chocovore17** [comment]
No idea why this did not work on my machine.
Thanks, everything works fine when I run it from a virtual machine.
