### ISSUE TITLE
2-parsers: recursive unary and unary plus

### ISSUE THREAD

**Issue by JaafarRammal** [LangProc/langproc-2019-lab#17]
What is the expected behavior for the following inputs:
```
- - 2
- - - - 4
3 - - - 4
```

I assume that alternating + and - should not be supported (even an opened plus such as "+2") since negation is the only unary to be supported as per [the spec](https://github.com/LangProc/langproc-2019-lab/tree/master/2-parsers#language-and-ast-overview)

**Comment by ymherklotz** [comment]
I believe there is only one interpretation for those, so it will apply the binary operator - when it has to and and the unary - otherwise. 

And yes, unary plus is not supported so there can't be any chains like that.

On 10 February 2020 16:02:10 GMT, Jaafar Rammal <notifications@github.com> wrote:
>What is the expected behavior for the following inputs:
>```
>- - 2
>- - - - 4
>3 - - - 4
>```
>
>I assume that alternating + and - should not be supported (even an
>opened plus such as "+2") since negation is the only unary to be
>supported as per [the
>spec](https://github.com/LangProc/langproc-2019-lab/tree/master/2-parsers#language-and-ast-overview)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LangProc/langproc-2019-lab/issues/17

-- 
Yann Herklotz
https://yannherklotz.com

**Comment by JaafarRammal** [comment]
Does that mean we get ( - ( - 2 ) )?

**Comment by tobhil98** [comment]
Yes
